language: php

php:
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.0
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source $PREFER_LOWEST
  - printf "\n" | pecl install imagick

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

notifications:
    on_success: never
    on_failure: always
